# Generated by Django 4.0.6 on 2022-07-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usermodel_first_name_alter_usermodel_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ('-created_at',), 'verbose_name': 'Інформація про користувача', 'verbose_name_plural': 'Інформація про користувача'},
        ),
    ]
