# Generated by Django 4.0.6 on 2022-07-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usermodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_id',
            field=models.BigIntegerField(blank=True),
        ),
    ]
